language: python
python:
  - "2.6"
  - "2.7"
services:
  - "riak"
cache:
  - "pip"
matrix:
  include:
    - python: "pypy"
      env: NO_COVERAGE="1"
install:
  - "pip install -r requirements.pip"
  - "pip install -r requirements-dev.pip"
  - "pip install coveralls"
  - "python setup.py install"
script:
  - if [ -z "$NO_COVERAGE" ]; then COVERAGE_CMD="coverage run --source=vumi_twilio_api"; else COVERAGE_CMD=""; fi
  - $COVERAGE_CMD `which trial` vumi_twilio_api
after_success:
    - if [ -z "$NO_COVERAGE" ]; then coveralls; fi
