language: python
python:
  - "2.6"
  - "2.7"
services:
  - "riak"
install:
  - "pip install -r requirements.pip"
  - "pip install -r requirements-dev.pip"
  - "pip install coveralls"
  - "python setup.py install"
script:
  - "coverage run --source=vumi_twilio_api `which trial` vumi_twilio_api"
after_success:
  - coveralls
