language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -r requirements.pip"
  - "pip install -r requirements-dev.pip"
  - "pip install coveralls"
  - "python setup.py install"
script:
  - "py.test vumi_twilio_api"
after_success:
  - coveralls
